// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtacavydkskzwoyfckhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0YWNhdnlka3NrendveWZja2hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NjM5NjgsImV4cCI6MjA3MjUzOTk2OH0.whg2OkCUsOXAuRwjVFdsGPg130S6HX7SbOaobLwPsFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});